# Generated by Django 2.0.5 on 2018-05-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('mem_ID', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('mem_Name', models.TextField()),
                ('mem_Class', models.IntegerField(max_length=5)),
                ('mem_Studentid', models.IntegerField(max_length=11)),
                ('mem_Department', models.TextField()),
                ('mem_Major', models.TextField()),
                ('mem_Dormitory', models.IntegerField(max_length=4)),
                ('mem_Room', models.IntegerField(max_length=4)),
                ('mem_Teacher', models.TextField()),
                ('mem_Phonenumber', models.IntegerField(max_length=13)),
                ('mem_Gender', models.BooleanField()),
                ('mem_Qqnumber', models.IntegerField(max_length=11)),
            ],
        ),
    ]
