# Generated by Django 2.0.5 on 2018-05-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mem_Class',
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mem_Department',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mem_Dormitory',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mem_Gender',
            field=models.TextField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mem_Major',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mem_Name',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='mem_Phonenumber',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mem_Qqnumber',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mem_Room',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mem_Studentid',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mem_Teacher',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
